name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none  # Pas de xdebug, pas de couverture

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: dist-${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
          restore-keys: |
            dist-${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Make phpstan executable
        run: chmod +x vendor/bin/phpstan

      - name: Make php-cs-fixer executable
        run: chmod +x vendor/bin/php-cs-fixer

      - name: Make phpunit executable
        run: chmod +x vendor/bin/phpunit

      - name: Lint code
        run: composer lint

      - name: Analyse static code
        run: composer analyse

      - name: Run tests
        run: composer test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - run: echo "Deploying to production..."
